name: openprices
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_overpass: ^1.1.0
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  latlong2: ^0.9.0
  meta: ^1.8.0
  openfoodfacts: ^3.3.2
  path: ^1.8.2 # 1.8.2 for flutter_test as of 2023-04-06
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.21.4
  coverage: ^1.6.2

flutter:

  uses-material-design: true

